name: Github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
      - name: "Build Github Pages"
        run: |
          mkdir -p target
          curl https://repo1.maven.org/maven2/org/commonmark/commonmark/0.26.0/commonmark-0.26.0.jar -o target/commonmark.jar
          curl https://repo1.maven.org/maven2/org/commonmark/commonmark-ext-gfm-tables/0.26.0/commonmark-ext-gfm-tables-0.26.0.jar -o target/commonmark-ext-gfm-tables.jar
          curl https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.19.2/jackson-core-2.19.2.jar -o target/jackson-core.jar
          curl https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.19.2/jackson-databind-2.19.2.jar -o target/jackson-databind.jar
          curl https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.19.2/jackson-annotations-2.19.2.jar -o target/jackson-annotations.jar
          echo 'Runner.main();/exit' | jshell --class-path target/commonmark.jar:target/commonmark-ext-gfm-tables.jar:target/jackson-databind.jar:target/jackson-core.jar:target/jackson-annotations.jar --startup site.generator.java
      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: target/pages/
